---
abstract: unknown
author:
  - unknown
build_requires:
  Cwd: 0
  ExtUtils::MakeMaker: 0
  File::Basename: 0
  Selenium::Remote::Driver: 0
  Test::Deep: 0
  Test::Fatal: 0
  Test::More: 0
  WWW::Selenium: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Selenium-PageObject
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Scalar::Util: 0
  Try::Tiny: 0
  perl: 5.010
version: 0.002
